// <auto-generated />
namespace MaaAahwanam.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migrations_date_07142016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrations_date_07142016));
        
        string IMigrationMetadata.Id
        {
            get { return "201607141004200_migrations_date_07142016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
