// <auto-generated />
namespace MaaAahwanam.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Indu_migrations_date_06152016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Indu_migrations_date_06152016));
        
        string IMigrationMetadata.Id
        {
            get { return "201606151128598_Indu_migrations_date_06152016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
