//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Admin_giftdesigns_multipleimages
    {
        public int id { get; set; }
        public int giftid { get; set; }
        public string Image { get; set; }
        public string Imageid { get; set; }
    
        public virtual MA_Giftdesigns MA_Giftdesigns { get; set; }
    }
}
