//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Admin_BiddingRequest
    {
        public MA_Admin_BiddingRequest()
        {
            this.MA_Bidding_Orders = new HashSet<MA_Bidding_Orders>();
        }
    
        public int BidID { get; set; }
        public int EventID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual MA_Events_Master MA_Events_Master { get; set; }
        public virtual ICollection<MA_Bidding_Orders> MA_Bidding_Orders { get; set; }
    }
}
