//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Admin_Invitationdesigns_multiimages
    {
        public int id { get; set; }
        public int Invitaitonid { get; set; }
        public string image { get; set; }
        public string imageid { get; set; }
    
        public virtual MA_Invi_Designs MA_Invi_Designs { get; set; }
    }
}
