//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Budgets_QuotationRequest
    {
        public MA_Budgets_QuotationRequest()
        {
            this.MA_Admin_QuotationRequest = new HashSet<MA_Admin_QuotationRequest>();
        }
    
        public int RequestID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<decimal> Budget { get; set; }
    
        public virtual ICollection<MA_Admin_QuotationRequest> MA_Admin_QuotationRequest { get; set; }
        public virtual MA_Events_Master MA_Events_Master { get; set; }
    }
}
