//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CartAddressbook
    {
        public int AddressBookID { get; set; }
        public Nullable<int> CarttItemID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> SoftCopy { get; set; }
        public string SoftCopyAddressBooks { get; set; }
        public Nullable<decimal> SoftCopyPrice { get; set; }
        public Nullable<int> HardCopy { get; set; }
        public string HardCopyAddressBooks { get; set; }
        public Nullable<decimal> HardCopyPrice { get; set; }
        public Nullable<int> Premium { get; set; }
        public string PremiumAddressBooks { get; set; }
        public Nullable<decimal> PremiumPrice { get; set; }
    
        public virtual MA_Events_Master MA_Events_Master { get; set; }
    }
}
