//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CommentDetails
    {
        public int CommentDetId { get; set; }
        public int CommentId { get; set; }
        public int UserLoginId { get; set; }
        public string CommentDetails { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public string AttachFileName { get; set; }
    
        public virtual MA_Comments MA_Comments { get; set; }
    }
}
