//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Comments
    {
        public MA_Comments()
        {
            this.MA_CommentDetails = new HashSet<MA_CommentDetails>();
        }
    
        public int CommentId { get; set; }
        public string ServiceId { get; set; }
        public string ServiceType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<MA_CommentDetails> MA_CommentDetails { get; set; }
    }
}
