//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CartItems_Master
    {
        public int CartItemID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> PricePerQty { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> VendorID { get; set; }
    
        public virtual MA_Events_Master MA_Events_Master { get; set; }
    }
}
