//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ExceptionLogs
    {
        public int ID { get; set; }
        public string ExceptionType { get; set; }
        public string ErrorMessage { get; set; }
        public string UrlPattern { get; set; }
        public System.DateTime Date { get; set; }
        public string LogType { get; set; }
        public int UserID { get; set; }
        public string IPAddress { get; set; }
        public string Browsertype { get; set; }
        public string URL { get; set; }
        public string usertype { get; set; }
    }
}
