//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Events_Master
    {
        public MA_Events_Master()
        {
            this.MA_Admin_BiddingRequest = new HashSet<MA_Admin_BiddingRequest>();
            this.MA_Bidding_Orders = new HashSet<MA_Bidding_Orders>();
            this.MA_BookNow_Orders = new HashSet<MA_BookNow_Orders>();
            this.MA_Budgets_QuotationRequest = new HashSet<MA_Budgets_QuotationRequest>();
            this.MA_CartAddressbook = new HashSet<MA_CartAddressbook>();
            this.MA_CartItems_Master = new HashSet<MA_CartItems_Master>();
            this.MA_EventDates = new HashSet<MA_EventDates>();
            this.MA_GiftDesign_Orders = new HashSet<MA_GiftDesign_Orders>();
            this.MA_Invitation_Orders = new HashSet<MA_Invitation_Orders>();
            this.MA_Quotation_Orders = new HashSet<MA_Quotation_Orders>();
        }
    
        public int EventID { get; set; }
        public string EventName { get; set; }
        public string ServiceType { get; set; }
        public string Preferences { get; set; }
        public string EventAddress { get; set; }
        public string EventLocation { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ServiceFrom { get; set; }
    
        public virtual ICollection<MA_Admin_BiddingRequest> MA_Admin_BiddingRequest { get; set; }
        public virtual ICollection<MA_Bidding_Orders> MA_Bidding_Orders { get; set; }
        public virtual ICollection<MA_BookNow_Orders> MA_BookNow_Orders { get; set; }
        public virtual ICollection<MA_Budgets_QuotationRequest> MA_Budgets_QuotationRequest { get; set; }
        public virtual ICollection<MA_CartAddressbook> MA_CartAddressbook { get; set; }
        public virtual ICollection<MA_CartItems_Master> MA_CartItems_Master { get; set; }
        public virtual ICollection<MA_EventDates> MA_EventDates { get; set; }
        public virtual ICollection<MA_GiftDesign_Orders> MA_GiftDesign_Orders { get; set; }
        public virtual ICollection<MA_Invitation_Orders> MA_Invitation_Orders { get; set; }
        public virtual ICollection<MA_Quotation_Orders> MA_Quotation_Orders { get; set; }
    }
}
