//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Enquiry
    {
        public int EnquiryId { get; set; }
        public string PersonName { get; set; }
        public string SenderEmailId { get; set; }
        public string SenderPhone { get; set; }
        public string EnquiryTitle { get; set; }
        public string EnquiryDetails { get; set; }
        public System.DateTime EnquiryDate { get; set; }
        public string EnquiryStatus { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
