//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ForgotPassword
    {
        public int Id { get; set; }
        public int UserLoginId { get; set; }
        public string UserName { get; set; }
        public bool ReqRaised { get; set; }
        public Nullable<System.DateTime> RaisedDate { get; set; }
    }
}
