//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Giftdesigns
    {
        public MA_Giftdesigns()
        {
            this.MA_Admin_giftdesigns_multipleimages = new HashSet<MA_Admin_giftdesigns_multipleimages>();
            this.MA_GiftDesign_Orders = new HashSet<MA_GiftDesign_Orders>();
        }
    
        public int Giftid { get; set; }
        public string Category { get; set; }
        public string Giftname { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string ImageId { get; set; }
        public Nullable<decimal> GiftCost { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> VendorId { get; set; }
    
        public virtual ICollection<MA_Admin_giftdesigns_multipleimages> MA_Admin_giftdesigns_multipleimages { get; set; }
        public virtual ICollection<MA_GiftDesign_Orders> MA_GiftDesign_Orders { get; set; }
    }
}
