//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_InviDesignPrices
    {
        public int PriceId { get; set; }
        public int DesignId { get; set; }
        public Nullable<decimal> EmailCost { get; set; }
        public Nullable<decimal> SmsCost { get; set; }
        public Nullable<decimal> PostCost { get; set; }
        public Nullable<decimal> PremiumCost { get; set; }
    
        public virtual MA_Invi_Designs MA_Invi_Designs { get; set; }
    }
}
