//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_IssueTickets
    {
        public MA_IssueTickets()
        {
            this.MA_Issue_Details = new HashSet<MA_Issue_Details>();
        }
    
        public int Ticket_Id { get; set; }
        public Nullable<int> UserLoginId { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public string Issue_Type { get; set; }
        public string Subject { get; set; }
        public string Severity { get; set; }
        public string Name { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
    
        public virtual ICollection<MA_Issue_Details> MA_Issue_Details { get; set; }
        public virtual MA_User_Login MA_User_Login { get; set; }
    }
}
