//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Invi_Designs
    {
        public MA_Invi_Designs()
        {
            this.MA_Admin_Invitationdesigns_multiimages = new HashSet<MA_Admin_Invitationdesigns_multiimages>();
            this.MA_InviDesignPrices = new HashSet<MA_InviDesignPrices>();
            this.MA_Invitation_Orders = new HashSet<MA_Invitation_Orders>();
        }
    
        public int DesignId { get; set; }
        public string Category { get; set; }
        public string DesignName { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string ImageId { get; set; }
        public Nullable<decimal> CardCost { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> VendorId { get; set; }
    
        public virtual ICollection<MA_Admin_Invitationdesigns_multiimages> MA_Admin_Invitationdesigns_multiimages { get; set; }
        public virtual MA_User_Login MA_User_Login { get; set; }
        public virtual ICollection<MA_InviDesignPrices> MA_InviDesignPrices { get; set; }
        public virtual ICollection<MA_Invitation_Orders> MA_Invitation_Orders { get; set; }
    }
}
