//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Issue_Details
    {
        public int Ticket_Commu_Id { get; set; }
        public int Ticket_Id { get; set; }
        public string Msg { get; set; }
        public string RepliedBy { get; set; }
        public Nullable<System.DateTime> ReplayedDate { get; set; }
    
        public virtual MA_IssueTickets MA_IssueTickets { get; set; }
    }
}
