//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Orders_Master
    {
        public MA_Orders_Master()
        {
            this.MA_Bidding_Orders = new HashSet<MA_Bidding_Orders>();
            this.MA_BookNow_Orders = new HashSet<MA_BookNow_Orders>();
            this.MA_GiftDesign_Orders = new HashSet<MA_GiftDesign_Orders>();
            this.MA_Invitation_Orders = new HashSet<MA_Invitation_Orders>();
            this.MA_Quotation_Orders = new HashSet<MA_Quotation_Orders>();
        }
    
        public int OrderId { get; set; }
        public decimal OrderAmt { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public Nullable<decimal> TotalTaxAmt { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public decimal PaidAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<MA_Bidding_Orders> MA_Bidding_Orders { get; set; }
        public virtual ICollection<MA_BookNow_Orders> MA_BookNow_Orders { get; set; }
        public virtual ICollection<MA_GiftDesign_Orders> MA_GiftDesign_Orders { get; set; }
        public virtual ICollection<MA_Invitation_Orders> MA_Invitation_Orders { get; set; }
        public virtual ICollection<MA_Quotation_Orders> MA_Quotation_Orders { get; set; }
    }
}
