//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_SavedCardDetails
    {
        public int CardID { get; set; }
        public string Nameoncard { get; set; }
        public string CardType { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> SecurityCode { get; set; }
        public string BankName { get; set; }
        public string TypeofPayment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatdDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
