//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_User_Vendor
    {
        public MA_User_Vendor()
        {
            this.MA_Vendor_Aminities = new HashSet<MA_Vendor_Aminities>();
            this.MA_Vendor_Images = new HashSet<MA_Vendor_Images>();
            this.MA_Vendor_Packages = new HashSet<MA_Vendor_Packages>();
            this.MA_VendorPayments = new HashSet<MA_VendorPayments>();
        }
    
        public int UserBusiId { get; set; }
        public int UserLoginId { get; set; }
        public string BusinessName { get; set; }
        public string BusinessDesc { get; set; }
        public Nullable<System.DateTime> BusinessEstDate { get; set; }
        public string BusinessPhone { get; set; }
        public string BusinessPhLand { get; set; }
        public string BusinessAddress { get; set; }
        public string BusinessLocation { get; set; }
        public string BusinessCity { get; set; }
        public string BusinessState { get; set; }
        public string BusinessZIP { get; set; }
        public string ServiceType { get; set; }
        public Nullable<int> Experience { get; set; }
        public string BusinessUrl { get; set; }
        public string BusinessStatus { get; set; }
        public string BusinessEmail { get; set; }
        public Nullable<System.DateTime> Requestdate { get; set; }
        public string TermsandConditions { get; set; }
        public Nullable<bool> BookNow { get; set; }
        public Nullable<bool> Quotation { get; set; }
        public Nullable<bool> Bidding { get; set; }
    
        public virtual MA_User_Login MA_User_Login { get; set; }
        public virtual ICollection<MA_Vendor_Aminities> MA_Vendor_Aminities { get; set; }
        public virtual ICollection<MA_Vendor_Images> MA_Vendor_Images { get; set; }
        public virtual ICollection<MA_Vendor_Packages> MA_Vendor_Packages { get; set; }
        public virtual ICollection<MA_VendorPayments> MA_VendorPayments { get; set; }
    }
}
