//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_User_AddBook
    {
        public int AddBookId { get; set; }
        public int UserLoginId { get; set; }
        public string PersonName { get; set; }
        public string PersonAddress { get; set; }
        public string PersonLocation { get; set; }
        public string PersonCity { get; set; }
        public string PersonPhone { get; set; }
        public string PersonEmail { get; set; }
    
        public virtual MA_User_Login MA_User_Login { get; set; }
    }
}
