//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_User_Details
    {
        public int UserDetailId { get; set; }
        public int UserLoginId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserPhone { get; set; }
        public string Url { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string UserImgId { get; set; }
        public string UserImgName { get; set; }
    
        public virtual MA_User_Login MA_User_Login { get; set; }
    }
}
