//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_User_Login
    {
        public MA_User_Login()
        {
            this.MA_Invi_Designs = new HashSet<MA_Invi_Designs>();
            this.MA_IssueTickets = new HashSet<MA_IssueTickets>();
            this.MA_User_AddBook = new HashSet<MA_User_AddBook>();
            this.MA_User_Details = new HashSet<MA_User_Details>();
            this.MA_User_Vendor = new HashSet<MA_User_Vendor>();
        }
    
        public int UserLoginId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserType { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<MA_Invi_Designs> MA_Invi_Designs { get; set; }
        public virtual ICollection<MA_IssueTickets> MA_IssueTickets { get; set; }
        public virtual ICollection<MA_User_AddBook> MA_User_AddBook { get; set; }
        public virtual ICollection<MA_User_Details> MA_User_Details { get; set; }
        public virtual ICollection<MA_User_Vendor> MA_User_Vendor { get; set; }
    }
}
