//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Vendor_Packages
    {
        public MA_Vendor_Packages()
        {
            this.MA_BookNow_Orders = new HashSet<MA_BookNow_Orders>();
        }
    
        public int VendorPackageId { get; set; }
        public int UserBusiId { get; set; }
        public string Packagename { get; set; }
        public string PackageDesc { get; set; }
        public System.DateTime PackageStartDate { get; set; }
        public System.DateTime PackageEndDate { get; set; }
        public Nullable<decimal> actualamount { get; set; }
        public Nullable<decimal> sellingamount { get; set; }
        public Nullable<decimal> dealamount { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public Nullable<decimal> tax { get; set; }
    
        public virtual ICollection<MA_BookNow_Orders> MA_BookNow_Orders { get; set; }
        public virtual MA_User_Vendor MA_User_Vendor { get; set; }
    }
}
