//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Vendor_Aminities
    {
        public int UserBusiAminitiesId { get; set; }
        public int UserBusiId { get; set; }
        public string UserAminitiesType { get; set; }
    
        public virtual MA_User_Vendor MA_User_Vendor { get; set; }
    }
}
