//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaaAahwanam.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MA_Admin_BiddingRequest> MA_Admin_BiddingRequest { get; set; }
        public virtual DbSet<MA_Admin_giftdesigns_multipleimages> MA_Admin_giftdesigns_multipleimages { get; set; }
        public virtual DbSet<MA_Admin_Invitationdesigns_multiimages> MA_Admin_Invitationdesigns_multiimages { get; set; }
        public virtual DbSet<MA_Admin_QuotationRequest> MA_Admin_QuotationRequest { get; set; }
        public virtual DbSet<MA_Admin_Testimonials> MA_Admin_Testimonials { get; set; }
        public virtual DbSet<MA_Admin_TestimonialsPath> MA_Admin_TestimonialsPath { get; set; }
        public virtual DbSet<MA_Bidding_Orders> MA_Bidding_Orders { get; set; }
        public virtual DbSet<MA_BookNow_Orders> MA_BookNow_Orders { get; set; }
        public virtual DbSet<MA_Budgets_QuotationRequest> MA_Budgets_QuotationRequest { get; set; }
        public virtual DbSet<MA_CartAddressbook> MA_CartAddressbook { get; set; }
        public virtual DbSet<MA_CartItems_Master> MA_CartItems_Master { get; set; }
        public virtual DbSet<MA_CommentDetails> MA_CommentDetails { get; set; }
        public virtual DbSet<MA_Comments> MA_Comments { get; set; }
        public virtual DbSet<MA_Enquiry> MA_Enquiry { get; set; }
        public virtual DbSet<MA_EventDates> MA_EventDates { get; set; }
        public virtual DbSet<MA_Events_Master> MA_Events_Master { get; set; }
        public virtual DbSet<MA_EventsandTips> MA_EventsandTips { get; set; }
        public virtual DbSet<MA_ExceptionLogs> MA_ExceptionLogs { get; set; }
        public virtual DbSet<MA_ForgotPassword> MA_ForgotPassword { get; set; }
        public virtual DbSet<MA_GiftDesign_Orders> MA_GiftDesign_Orders { get; set; }
        public virtual DbSet<MA_Giftdesigns> MA_Giftdesigns { get; set; }
        public virtual DbSet<MA_Invi_Designs> MA_Invi_Designs { get; set; }
        public virtual DbSet<MA_InviDesignPrices> MA_InviDesignPrices { get; set; }
        public virtual DbSet<MA_Invitation_Orders> MA_Invitation_Orders { get; set; }
        public virtual DbSet<MA_Issue_Details> MA_Issue_Details { get; set; }
        public virtual DbSet<MA_IssueTickets> MA_IssueTickets { get; set; }
        public virtual DbSet<MA_Orders_Master> MA_Orders_Master { get; set; }
        public virtual DbSet<MA_Payment_Carddetails> MA_Payment_Carddetails { get; set; }
        public virtual DbSet<MA_Quotation_Orders> MA_Quotation_Orders { get; set; }
        public virtual DbSet<MA_Quotation_Vendors> MA_Quotation_Vendors { get; set; }
        public virtual DbSet<MA_Reviews> MA_Reviews { get; set; }
        public virtual DbSet<MA_SavedCardDetails> MA_SavedCardDetails { get; set; }
        public virtual DbSet<MA_SiteFaq> MA_SiteFaq { get; set; }
        public virtual DbSet<MA_Subscription> MA_Subscription { get; set; }
        public virtual DbSet<MA_User_AddBook> MA_User_AddBook { get; set; }
        public virtual DbSet<MA_User_Details> MA_User_Details { get; set; }
        public virtual DbSet<MA_User_Login> MA_User_Login { get; set; }
        public virtual DbSet<MA_User_Vendor> MA_User_Vendor { get; set; }
        public virtual DbSet<MA_UserLogInTimings> MA_UserLogInTimings { get; set; }
        public virtual DbSet<MA_Vendor_Aminities> MA_Vendor_Aminities { get; set; }
        public virtual DbSet<MA_Vendor_Images> MA_Vendor_Images { get; set; }
        public virtual DbSet<MA_Vendor_Packages> MA_Vendor_Packages { get; set; }
        public virtual DbSet<MA_VendorPayments> MA_VendorPayments { get; set; }
    
        public virtual ObjectResult<MA_Admin_dashboardcounts_Result> MA_Admin_dashboardcounts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MA_Admin_dashboardcounts_Result>("MA_Admin_dashboardcounts");
        }
    
        public virtual ObjectResult<SP_ADDRESSBOOK_Result> SP_ADDRESSBOOK(Nullable<int> userLoginId, Nullable<int> ntype)
        {
            var userLoginIdParameter = userLoginId.HasValue ?
                new ObjectParameter("UserLoginId", userLoginId) :
                new ObjectParameter("UserLoginId", typeof(int));
    
            var ntypeParameter = ntype.HasValue ?
                new ObjectParameter("ntype", ntype) :
                new ObjectParameter("ntype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADDRESSBOOK_Result>("SP_ADDRESSBOOK", userLoginIdParameter, ntypeParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_ORDERDITEMS_USER_Result> SP_ADMIN_ORDERDITEMS_USER(Nullable<int> oRDERID)
        {
            var oRDERIDParameter = oRDERID.HasValue ?
                new ObjectParameter("ORDERID", oRDERID) :
                new ObjectParameter("ORDERID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_ORDERDITEMS_USER_Result>("SP_ADMIN_ORDERDITEMS_USER", oRDERIDParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_ORDERS_Result> SP_ADMIN_ORDERS(Nullable<int> oRDERID, Nullable<int> uSERID)
        {
            var oRDERIDParameter = oRDERID.HasValue ?
                new ObjectParameter("ORDERID", oRDERID) :
                new ObjectParameter("ORDERID", typeof(int));
    
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_ORDERS_Result>("SP_ADMIN_ORDERS", oRDERIDParameter, uSERIDParameter);
        }
    
        public virtual ObjectResult<SP_ADMIN_Servicerequest_Result> SP_ADMIN_Servicerequest(string type, Nullable<int> nType, Nullable<int> id)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var nTypeParameter = nType.HasValue ?
                new ObjectParameter("nType", nType) :
                new ObjectParameter("nType", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ADMIN_Servicerequest_Result>("SP_ADMIN_Servicerequest", typeParameter, nTypeParameter, idParameter);
        }
    
        public virtual ObjectResult<Sp_Admin_UserProfile_Result> Sp_Admin_UserProfile(Nullable<int> ticket, Nullable<int> ntype)
        {
            var ticketParameter = ticket.HasValue ?
                new ObjectParameter("ticket", ticket) :
                new ObjectParameter("ticket", typeof(int));
    
            var ntypeParameter = ntype.HasValue ?
                new ObjectParameter("ntype", ntype) :
                new ObjectParameter("ntype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Admin_UserProfile_Result>("Sp_Admin_UserProfile", ticketParameter, ntypeParameter);
        }
    
        public virtual ObjectResult<SP_CART_ITEMSVIEW_Result> SP_CART_ITEMSVIEW(Nullable<int> uSERID, Nullable<int> nTYPE)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(int));
    
            var nTYPEParameter = nTYPE.HasValue ?
                new ObjectParameter("NTYPE", nTYPE) :
                new ObjectParameter("NTYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CART_ITEMSVIEW_Result>("SP_CART_ITEMSVIEW", uSERIDParameter, nTYPEParameter);
        }
    
        public virtual ObjectResult<SP_COUNTS_TICKETS_AND_NOTIFICATIONS_Result> SP_COUNTS_TICKETS_AND_NOTIFICATIONS(Nullable<int> uSERID)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_COUNTS_TICKETS_AND_NOTIFICATIONS_Result>("SP_COUNTS_TICKETS_AND_NOTIFICATIONS", uSERIDParameter);
        }
    
        public virtual int SP_DEALSEARCH(Nullable<int> nTYPE, string sERVICETYPE, string businessLocation)
        {
            var nTYPEParameter = nTYPE.HasValue ?
                new ObjectParameter("NTYPE", nTYPE) :
                new ObjectParameter("NTYPE", typeof(int));
    
            var sERVICETYPEParameter = sERVICETYPE != null ?
                new ObjectParameter("SERVICETYPE", sERVICETYPE) :
                new ObjectParameter("SERVICETYPE", typeof(string));
    
            var businessLocationParameter = businessLocation != null ?
                new ObjectParameter("BusinessLocation", businessLocation) :
                new ObjectParameter("BusinessLocation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DEALSEARCH", nTYPEParameter, sERVICETYPEParameter, businessLocationParameter);
        }
    
        public virtual ObjectResult<SP_DEALSLIST_Result> SP_DEALSLIST(Nullable<int> nTYPE, string sERVICETYPE, string businessLocation)
        {
            var nTYPEParameter = nTYPE.HasValue ?
                new ObjectParameter("NTYPE", nTYPE) :
                new ObjectParameter("NTYPE", typeof(int));
    
            var sERVICETYPEParameter = sERVICETYPE != null ?
                new ObjectParameter("SERVICETYPE", sERVICETYPE) :
                new ObjectParameter("SERVICETYPE", typeof(string));
    
            var businessLocationParameter = businessLocation != null ?
                new ObjectParameter("BusinessLocation", businessLocation) :
                new ObjectParameter("BusinessLocation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DEALSLIST_Result>("SP_DEALSLIST", nTYPEParameter, sERVICETYPEParameter, businessLocationParameter);
        }
    
        public virtual ObjectResult<SP_EVENT_BEAUTY_HEALTH_LIST_Result> SP_EVENT_BEAUTY_HEALTH_LIST(Nullable<int> nTYPE, string tYPE)
        {
            var nTYPEParameter = nTYPE.HasValue ?
                new ObjectParameter("NTYPE", nTYPE) :
                new ObjectParameter("NTYPE", typeof(int));
    
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EVENT_BEAUTY_HEALTH_LIST_Result>("SP_EVENT_BEAUTY_HEALTH_LIST", nTYPEParameter, tYPEParameter);
        }
    
        public virtual ObjectResult<SP_EVENTDETAILSANDEVENTDATES_Result> SP_EVENTDETAILSANDEVENTDATES(Nullable<int> eVENTID)
        {
            var eVENTIDParameter = eVENTID.HasValue ?
                new ObjectParameter("EVENTID", eVENTID) :
                new ObjectParameter("EVENTID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EVENTDETAILSANDEVENTDATES_Result>("SP_EVENTDETAILSANDEVENTDATES", eVENTIDParameter);
        }
    
        public virtual ObjectResult<SP_TESTIMONIALSLIST_Result> SP_TESTIMONIALSLIST(Nullable<int> nTYPE)
        {
            var nTYPEParameter = nTYPE.HasValue ?
                new ObjectParameter("NTYPE", nTYPE) :
                new ObjectParameter("NTYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TESTIMONIALSLIST_Result>("SP_TESTIMONIALSLIST", nTYPEParameter);
        }
    
        public virtual ObjectResult<SP_TICKETLIST_Result> SP_TICKETLIST(Nullable<int> ntype, Nullable<int> ticket_Id)
        {
            var ntypeParameter = ntype.HasValue ?
                new ObjectParameter("ntype", ntype) :
                new ObjectParameter("ntype", typeof(int));
    
            var ticket_IdParameter = ticket_Id.HasValue ?
                new ObjectParameter("Ticket_Id", ticket_Id) :
                new ObjectParameter("Ticket_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TICKETLIST_Result>("SP_TICKETLIST", ntypeParameter, ticket_IdParameter);
        }
    
        public virtual ObjectResult<SP_TicketsUserList_Result> SP_TicketsUserList(Nullable<int> userLoginId, Nullable<int> ntype)
        {
            var userLoginIdParameter = userLoginId.HasValue ?
                new ObjectParameter("UserLoginId", userLoginId) :
                new ObjectParameter("UserLoginId", typeof(int));
    
            var ntypeParameter = ntype.HasValue ?
                new ObjectParameter("ntype", ntype) :
                new ObjectParameter("ntype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TicketsUserList_Result>("SP_TicketsUserList", userLoginIdParameter, ntypeParameter);
        }
    
        public virtual ObjectResult<sp_vendorlist_Result> sp_vendorlist(Nullable<int> ntype, Nullable<int> vendorid)
        {
            var ntypeParameter = ntype.HasValue ?
                new ObjectParameter("ntype", ntype) :
                new ObjectParameter("ntype", typeof(int));
    
            var vendoridParameter = vendorid.HasValue ?
                new ObjectParameter("vendorid", vendorid) :
                new ObjectParameter("vendorid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vendorlist_Result>("sp_vendorlist", ntypeParameter, vendoridParameter);
        }
    }
}
